name: notalone
description: "Transcription de conversations de groupe en temps réel pour personnes sourdes et malentendantes. 100 % réseau local."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_onnxruntime: ^1.8.2
  meta: ^1.18.0
  mobile_scanner: ^7.3.0
  pretty_qr_code: ^3.6.0
  record: ^7.1.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.5.5
  very_good_analysis: ^10.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/models/
